//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VPKSoft.VersionCheck.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VPKSoft.VersionCheck.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the simple tab-delimited localization file.
        ///As you can see only the &quot;[]&quot; tags and tab delimited key-value pairs matter for the localization.
        ///The tab-delimited text can also include comments, etc. by adding a new tab-delimited field.
        ///[en-US]
        ///txtText	About - {0}
        ///txtOK	OK
        ///txtDescription	Description:
        ///txtCompanyName	Company name:
        ///txtCopyright	Copyright:
        ///txtProductName	Product name:
        ///txtVersion	Version:
        ///txtLicense	License:
        ///txtCheck	Check version:
        ///txtClickCheck	click to check
        ///txtCheckNA	N/A
        ///t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string about_dialog_localization_txt {
            get {
                return ResourceManager.GetString("about_dialog_localization.txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the simple tab-delimited localization file.
        ///As you can see only the &quot;[]&quot; tags and tab delimited key-value pairs matter for the localization.
        ///The tab-delimited text can also include comments, etc. by adding a new tab-delimited field.
        ///[en-US]
        ///txtDownload	Download:
        ///txtPercentageSymbol	%
        ///txtMegabytes	MB
        ///txtMegabytesPerSeconds	Speed (MB/s):
        ///txtCancel	Cancel
        ///[fi-FI]
        ///txtDownload	Lataus:
        ///txtPercentageSymbol	%
        ///txtMegabytes	MB
        ///txtMegabytesPerSeconds	Nopeus (MT/s):
        ///txtCancel	Peruuta
        ///.
        /// </summary>
        internal static string download_dialog_localization {
            get {
                return ResourceManager.GetString("download_dialog_localization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OK {
            get {
                object obj = ResourceManager.GetObject("OK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the simple tab-delimited localization file.
        ///As you can see only the &quot;[]&quot; tags and tab delimited key-value pairs matter for the localization.
        ///The tab-delimited text can also include comments, etc. by adding a new tab-delimited field.
        ///[en-US]
        ///txtNewVersionTitle	A new version of the &apos;{0}&apos; software is available!
        ///txtCurrentVersion	Current version:
        ///txtNewVersion	New version:
        ///txtReleaseDateTime	Release date/time:
        ///txtReleaseChanges	Release changes:
        ///txtUpdateSoftware	Update the software
        ///txtCancel	C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tab_deli_localization {
            get {
                return ResourceManager.GetString("tab_deli_localization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap VPKSoftLogo_App {
            get {
                object obj = ResourceManager.GetObject("VPKSoftLogo_App", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
