//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VPKSoft.VersionCheck.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VPKSoft.VersionCheck.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OK {
            get {
                object obj = ResourceManager.GetObject("OK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the simple tab-delimited localization file.
        ///As you can see only the &quot;[]&quot; tags and tab delimited key-value pairs matter for the localization.
        ///The tab-delimited text can also include comments, etc. by adding a new tab-delimited field.
        ///[en-US]
        ///txtNewVersionTitle	A new version of the &apos;{0}&apos; software is available!
        ///txtCurrentVersion	Current version:
        ///txtNewVersion	New version:
        ///txtReleaseDateTime	Release date/time:
        ///txtReleaseChanges	Release changes:
        ///txtUpdateSoftware	Update the software
        ///txtCancel	C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tab_deli_localization {
            get {
                return ResourceManager.GetString("tab_deli_localization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text=About - {0}
        ///OK=OK
        ///Description=Description:
        ///CompanyName=Company name:
        ///Copyright=Copyright:
        ///ProductName=Product name:
        ///Version=Version:
        ///License=License:
        ///Check=Check version:
        ///ClickCheck=click to check
        ///CheckNA=N/A
        ///CheckDownload=Download ({0}).
        /// </summary>
        internal static string texts_en_US {
            get {
                return ResourceManager.GetString("texts_en_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text=Tietoja - {0}
        ///OK=OK
        ///Description=Kuvaus:
        ///CompanyName=Tekijän nimi:
        ///Copyright=Tekijänoikeus:
        ///ProductName=Tuotteen nimi:
        ///Version=Versio:
        ///License=Lisenssi:
        ///Check=Tarkista versio:
        ///ClickCheck=klikkaa tarkistaaksesi
        ///CheckNA=ei saatavilla
        ///CheckDownload=Lataa ({0}).
        /// </summary>
        internal static string texts_fi_FI {
            get {
                return ResourceManager.GetString("texts_fi_FI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap VPKSoftLogo_App {
            get {
                object obj = ResourceManager.GetObject("VPKSoftLogo_App", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
